### ISSUE TITLE
Benchmark Page Doesn't Work in Safari 9

### ISSUE THREAD

**Issue by killercup** [autumnai/autumnai.com#2]
I'm using Safari Version 9.0.3 (11601.4.4) on OS X 10.11.3 and the page http://autumnai.com/deep-learning-benchmarks.html doesn't work for me.

The developer tools tell me, that

```
TypeError: Object is not a constructor (evaluating 'new Promise') fetchbenchmarks.js:995
(anonyme Funktion)benchmarks.js:592
(anonyme Funktion)benchmarks.js:659
__webpack_require__benchmarks.js:544
(anonyme Funktion)benchmarks.js:567
(anonyme Funktion)benchmarks.js:568
```

and that `fetchbenchmarks.js:995` is:

``` js
return new Promise(function(resolve, reject) {
```

This makes me wonder whether you are depending on some functionality of ES2015 Promises which Safari does not support (even though it includes Promise support) or if you use a Promise-shim which does not work with Safari.

I see in you `build.js` you are using webpack's `ProvidePlugin` for `es6-promise` and a really complex import call for `whatwg-fetch`. Might I suggest trying to add `import 'es6-promise'` directly?

**Comment by MichaelHirn** [comment]
Thank you for reporting the issue @killercup. 

I couldn't really test if it works now, but your suggestion seemed to be correct. Let me know if the bug still exists on http://autumnai.com/deep-learning-benchmarks.html

**Comment by killercup** [comment]
> I couldn't really test if it works now

Well, then this is karma: Safari now `Can't find variable: fetch` :wink:

It looks like the aforementioned `whatwg-fetch` is not included in `benchmarks.js`.

**Comment by killercup** [comment]
Also: I'm pretty sure you can easily test this on any iOS device by activating the debug console in Safari's settings.

**Comment by MichaelHirn** [comment]
That's so weird. I am not sure, how this can only be a problem for Safari (9).

I might need some more of your help with aiming, though. :smile: 
I am here on a linux/arch and an Android phone. Will retry tomorrow, maybe I can borrow a mac.

**Comment by killercup** [comment]
Are you per chance just using browsers that include both Promise and fetch?
The latest chrome and Firefox might not need the poky fills.

I'm pretty sure it's some small thing. Now that I've invested some time, I
kinda want to fix it, though. I'll have a look at it later :)

MJ Hirn notifications@github.com schrieb am Mo., 7. März 2016 um 18:58:
